/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '杨恺' at '16-10-7 下午3:09' with Gradle 2.8
 *
 * @author 杨恺, @date 16-10-7 下午3:09
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
